spring.application.name=ecommerce

# caminho da conexão
spring.datasource.url=jdbc:mysql://localhost:3306/aula_web?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
# Nome do usuário
spring.datasource.username=juan
# Senha do usuário
spring.datasource.password=123@Mudar
# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Estrategia de criação
spring.jpa.hibernate.ddl-auto=create
# Exibição de SQL
spring.jpa.show-sql=true
# Formatação dp SQL
spring.jpa.properties.hibernate.format_sql=true
#Dialeto
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
